language: python
branches:
  except:
  - gh-pages
matrix:
  include:
  - python: 3.4
    env: TOXENV=3.4,check,doc_travis
  - python: 2.7
    env: TOXENV=2.7,check,doc_travis
before_install:
- sudo apt-get update -qq
- sudo apt-get install -y git
- sudo apt-get install -y xsltproc
- sudo apt-get install -y genisoimage
- sudo apt-get install -y enchant
install:
- pip install --upgrade pip
- pip install -r .travis.requirements.txt
script:
- tox
# target disabled because documentation is in line with
# with master branch and not with the version maintained
# in sles. A deplyoment of the documentation from here
# will toggle the state from master which is unwanted
# after_success:
# - tox -e doc_travis_deploy
